---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: isk-reloader
  namespace: isk-reloader
spec:
  interval: 1m0s
  ref:
    branch: all-nsps-isk-reloader
  url: https://github.com/eyerene14/isk-reloader
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: isk-reloader
  namespace: isk-reloader
spec:
  interval: 2m0s
  path: ./isk-reloader
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: isk-reloader
