---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sldx-sec-app
  namespace: isk-sldx
spec:
  interval: 1m0s
  ref:
    branch: ij-local-docker-dev 
  url: https://scm.starbucks.com/ijaramil/isk-sldx-demo.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sldx-sec-app
  namespace:  isk-sldx
spec:
  interval: 2m0s
  path: ./deploy/dev
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: sldx-sec-app